package com.softwire.crossword.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called clueRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ClueRepository clueRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewClue(@RequestParam String clue,
                      @RequestParam String description
                      /*RequestParam String topic,
                      @RequestParam String style,
                      @RequestParam String author,
                      @RequestParam Integer difficulty*/) {
        Clue newClue = new Clue();
        newClue.setClue(clue);
        newClue.setDescription(description);
        /*newClue.setTopic(topic);
        newClue.setStyle(style);
        newClue.setAuthor(author);
        newClue.setDifficulty(difficulty);*/
        clueRepository.save(newClue);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Clue> getAllClues() {
        // This returns a JSON or XML with the clues
        return clueRepository.findAll();
    }
}